version: '3.8'

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    ports:
      - "54321:54321"   # Panel port
      - "8443:8443"       # Xray/V2Ray default
      - "80:80"         # Optional, for redirect or config
    volumes:
      - 3xui-data:/etc/x-ui
    restart: always

volumes:
  3xui-data:
